/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppButton {
        /**
          * @default false
         */
        "blackVariant": boolean;
        /**
          * @default false
         */
        "blackVariantSecondary": boolean;
        /**
          * States
          * @default false
         */
        "disabled": boolean;
        /**
          * @default false
         */
        "error": boolean;
        /**
          * @default false
         */
        "externalLink": boolean;
        /**
          * Link
         */
        "href"?: string;
        /**
          * Icon class
         */
        "icon"?: string;
        /**
          * Label text
         */
        "label": string;
        /**
          * @default false
         */
        "lightPrimary": boolean;
        /**
          * @default false
         */
        "loading": boolean;
        /**
          * @default false
         */
        "outline": boolean;
        /**
          * Variants
          * @default true
         */
        "primary": boolean;
        /**
          * Size
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'xlarge';
        "width"?: string | number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface AppButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppButtonElement;
}
declare global {
    interface HTMLAppButtonElementEventMap {
        "buttonClick": void;
    }
    interface HTMLAppButtonElement extends Components.AppButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppButtonElementEventMap>(type: K, listener: (this: HTMLAppButtonElement, ev: AppButtonCustomEvent<HTMLAppButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppButtonElementEventMap>(type: K, listener: (this: HTMLAppButtonElement, ev: AppButtonCustomEvent<HTMLAppButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppButtonElement: {
        prototype: HTMLAppButtonElement;
        new (): HTMLAppButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-button": HTMLAppButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppButton {
        /**
          * @default false
         */
        "blackVariant"?: boolean;
        /**
          * @default false
         */
        "blackVariantSecondary"?: boolean;
        /**
          * States
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "error"?: boolean;
        /**
          * @default false
         */
        "externalLink"?: boolean;
        /**
          * Link
         */
        "href"?: string;
        /**
          * Icon class
         */
        "icon"?: string;
        /**
          * Label text
         */
        "label": string;
        /**
          * @default false
         */
        "lightPrimary"?: boolean;
        /**
          * @default false
         */
        "loading"?: boolean;
        /**
          * Click event
         */
        "onButtonClick"?: (event: AppButtonCustomEvent<void>) => void;
        /**
          * @default false
         */
        "outline"?: boolean;
        /**
          * Variants
          * @default true
         */
        "primary"?: boolean;
        /**
          * Size
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'xlarge';
        "width"?: string | number;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "app-button": AppButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-button": LocalJSX.AppButton & JSXBase.HTMLAttributes<HTMLAppButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
